<?php

/**
 * @file
 * This module allows subtitles to be added to blocks
 **/

/**
 * Implements hook_form_alter 
 **/
function block_subtitle_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'block_add_block_form' || $form_id == 'block_admin_configure') {
    $block->module = $form['module']['#value'];
    $block->delta = $form['delta']['#value'];
    
    $subtitle = _block_subtitle_get_subtitle($block);
    
    $form['settings']['block_subtitle'] = array(
      '#type' => 'textfield',
      '#title' => t('Subtitle'),
      '#default_value' => $subtitle,
      '#description' => t('Subtitle for the block. Leave blank if you do not need a subtitle.'),
      '#weight' => -17,
    );
        
   $form['#submit'][] = 'block_subtitle_submit';
  }
}

/**
 * Custom submit handler for block_subtitle
 */
function block_subtitle_submit($form, &$form_state) {
  $module = $form_state['values']['module'];
  $delta = ($form_state['values']['delta']) ? $form_state['values']['delta'] : block_subtitle_get_delta($module);
  $subtitle = $form_state['values']['block_subtitle'];
  
  //Save Subtitle
  if ($module && ($delta || $delta == 0)) {
    $block_name = $module .'_'. $delta;
    //Delete subtitle if blank
    if (strlen($subtitle) == 0 || $subtitle == '') {
      _block_subtitle_delete($block_name);
    }
    else {
      _block_subtitle_save($block_name, $subtitle);
    }
  }
}

/**
 * Function to get the subtitle of a block
 * 
 * @param
 *  $block - Block name
 * @return
 *  the block subtitle
 **/
function _block_subtitle_get_subtitle($block) {
  if (!isset($block->module) && !isset($block->delta)) {
    return FALSE;
  }
  $varname = 'block_subtitle_' . $block->module .'_'. $block->delta;
  
  return variable_get($varname, NULL);
}

/**
 * Function to save a subtitle
 **/
function _block_subtitle_save($block_name, $value) {
  variable_set('block_subtitle_'. $block_name, $value);
}

/** 
 * Function to delete a subtitle
 * @param string $blockname
 * @return void
 **/
function _block_subtitle_delete($block_name){
  variable_set('block_subtitle_'. $block_name, '');
}

/**
 * Implementation of hook_preprocess_block
**/
function block_subtitle_preprocess_block(&$vars, $hook) {  
  if ($hook == 'block') {
    $vars['block']->subtitle = _block_subtitle_get_subtitle($vars['block']);
  }
}

/**
 * Gets the delta for custom blocks
 */
function block_subtitle_get_delta($module) {
  //get last delta
  $result = db_query('SELECT delta FROM {blocks} WHERE module = ":module" ORDER BY bid DESC LIMIT 1', array(
    ':module' => $module)
  );
  $data = db_fetch_object($result);
  
  return $data->delta;
}